[package]
name = "rok-page"
version = "0.1.0"
authors = ["S.C. Lorentz <felipe.lorentz@outlook.com.br>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
actix-files = "0.6.6"
actix-web = "4.8.0"
wasm-bindgen = "0.2"
